### ISSUE TITLE
Error when testing

### ISSUE THREAD

**Issue by Cerzs** [TesterTesterov/bsiTool#1]
Hello!

I was testing "Amairo Chocolata", the tool extract and import just fine, but the game crashes.
![imagen](https://user-images.githubusercontent.com/44489935/103030754-cd4d2b00-4532-11eb-9174-72ba6a801c94.png)

[Here's the script if you want to take a look](https://cdn.discordapp.com/attachments/687043665289412705/791388753112465438/scripts.rar).

**Comment by TesterTesterov** [comment]
Hmm... I guess I know what's the problem.

Fixed (probably).
Try the latest commit's program.

===
If it's not this problem, then I'll probably need to test with the game itself.

**Comment by Cerzs** [comment]
@TesterTesterov Got the same error. I can send you a link if you want
