### ISSUE TITLE
Oshirabu error

### ISSUE THREAD

**Issue by Blitz0001** [TesterTesterov/bsiTool#3]
Good evening, thanks for the tool! I was using it with the game Oshirabu: Waifus over Husbandos, but when repacking I got the following error:
![image](https://user-images.githubusercontent.com/69373908/106559339-05696580-6504-11eb-871f-32442db94df6.png)

Is it possible to fix it? 
Here's the script just in case:
https://drive.google.com/file/d/14SxlPKUpNFI0idu52zGCUlpjTqU-G7tP/view

Thanks in advance.

**Comment by TesterTesterov** [comment]
Hmm...
There was [rather close problem](https://github.com/TesterTesterov/bsiTool/issues/1) to it.

Try do the same first.

**Comment by Blitz0001** [comment]
Thank you for answering. I tried what you said, but i'm getting the same error:
![image](https://user-images.githubusercontent.com/69373908/106640956-6e34fa00-6565-11eb-831b-56e4e98df49c.png)

**Comment by Blitz0001** [comment]
It worked! Thank you very much.
